### ISSUE TITLE
problem with PyInstaller

### ISSUE THREAD

**Issue by Zenahr** [snguyenthanh/better_profanity#38]
I'm packaging a script as an executable via PyInstaller.

better_profanity always looks for a file in this directory: `C:\\Users\\<USERNAME>\\AppData\\Local\\Temp\\_MEI199002\\better_profanity\\alphabetic_unicode.json`

Is there a way to select the file for that manually as we can for the wordlist?

<details>
  <summary>Traceback:</summary>
<pre>
Traceback (most recent call last):
  File "gui.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "app\app.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "better_profanity\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "better_profanity\better_profanity.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "better_profanity\constants.py", line 14, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\<USERNAME>\\AppData\\Local\\Temp\\_MEI199002\\better_profanity\\alphabetic_unicode.json'
</pre>
</details>

**Comment by jcbrockschmidt** [comment]
Have you tried using `--add-data` like in [this solution](https://github.com/pyinstaller/pyinstaller/issues/5522#issuecomment-770858489)? If that doesn't work, could you provide steps to reproduce this error?

**Comment by ZenaMel** [comment]
@jcbrockschmidt Yes, I did. I'll try to get back to you to reproduce. However, I've moved on to an alternative lib.

**Comment by jcbrockschmidt** [comment]
> @jcbrockschmidt Yes, I did. I'll try to get back to you to reproduce. However, I've moved on to an alternative lib.

In that case, it's probably because we're reading files in a non-standardized way. I suspect we'll want to do something [like this](https://stackoverflow.com/questions/6028000/how-to-read-a-static-file-from-inside-a-python-package). Labeling as a bug.

**Comment by jonathan-attard** [comment]
Can you use this?

`bundle_dir = getattr(sys, '_MEIPASS', os.path.abspath(os.path.dirname(__file__)))`
`file_path = os.path.join(bundle_dir, file_name)`

**Comment by WilHall** [comment]
The above solutions do not work for me on the latest pyinstaller with Python 3.5 - the `.env` file is still not found.
